# Development compose file.

version: '2'
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.php7
    ports:
     - "127.0.0.1:8082:80"
    volumes:
     - .:/var/www/html:cached
    links:
     - db
    environment:
     - ENVIRONMENT=DEV
     - DRUPAL_INSTALL=TRUE
     - HTPASSWD_USER
     - HTPASSWD_PASSWORD
     - XDEBUG_CONFIG=remote_host=docker.for.mac.host.internal remote_connect_back=0
     - PHP_IDE_CONFIG=serverName=localhost

  db:
    image: mariadb
#    ports:
#      - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=docker
     - MYSQL_DATABASE=drupal
     - MYSQL_USER=drupal
     - MYSQL_PASSWORD=drupalpw

#  blackfire:
#    image: blackfire/blackfire
#    environment:
#      BLACKFIRE_SERVER_ID:
#      BLACKFIRE_SERVER_TOKEN:

  selenium:
    image: selenium/standalone-chrome
    network_mode: service:app
